### ISSUE TITLE
必要なデータを洗い出してER図書く

### ISSUE THREAD

**Issue by riwn** [fokkuma/praisehub#2]
## 必須テーブル
- ユーザー
- Tweet的なやつ
## 機能によって必要なテーブル
- フォロー
- 褒め履歴
- コメント

**Comment by fokkuma** [comment]
![praisehub_ER図](https://user-images.githubusercontent.com/49399218/83319390-0c571e80-a279-11ea-924c-8f3276fac9e6.PNG)

書きました

**Comment by fokkuma** [comment]
1. Tweetテーブル名をPraisedに変更
2. Praiseテーブル名をGoodjobに変更

![praisehub_ER図v0 02](https://user-images.githubusercontent.com/49399218/83321600-af189880-a28b-11ea-88b3-8e6ee8b8154e.PNG)

**Comment by fokkuma** [comment]
![praisehub_ER図v0 03](https://user-images.githubusercontent.com/49399218/83322109-fd2f9b00-a28f-11ea-8a39-e9ad5a6014f3.PNG)
